name: Elisa Claire Alemán Carreón
# markdown: kramdown

# Google Analytics
google_analytics: G-E5QN7E31DR

url: "https://elisa-aleman.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

exclude: [
  "logs", 
  "assets/blog",
  "en/_posts", "es/_posts", "jp/_posts",
  "_layouts/en_default_future.html", "_layouts/es_default_future.html", "_layouts/jp_default_future.html"
]

#Publishing defaults
show_drafts: false
future: false
timezone: Asia/Tokyo
